# SPDX-License-Identifier: DaoTi-Research-1.0
# Copyright (c) 2026 独立研究者，知白
# 本文件受道体研究许可证 v1.0 约束，禁止逆向工程和再分发
# 详见 LICENSE 文件

import subprocess
import sys
import os
import platform
import secrets


def _inject_compile_time_key(script_dir: str) -> str:
    """生成编译期固化的 XOR key + 预加密的阈值常量，写入 _key_generated.py（gitignore）。

    Nuitka 编译时该文件被固化为机器码常量，防止 strings 提取明文阈值。
    """
    import base64
    project_root = os.path.abspath(os.path.join(script_dir, "..", ".."))
    key_file = os.path.join(project_root, "src", "daoti_xuandun", "_key_generated.py")
    key_bytes = secrets.token_bytes(32)

    secure_values = {
        "prototype_distance_threshold_default": "0.65",
        "prototype_distance_threshold_basic": "0.50",
        "prototype_distance_threshold_standard": "0.45",
        "prototype_distance_threshold_strict": "0.35",
        "reject_boundary_multiplier_default": "3.0",
        "reject_boundary_multiplier_basic": "2.0",
        "reject_boundary_multiplier_standard": "2.2",
        "reject_boundary_multiplier_strict": "2.5",
        "structural_anomaly_threshold_default": "0.35",
        "structural_anomaly_threshold_basic": "0.40",
        "structural_anomaly_threshold_standard": "0.30",
        "structural_anomaly_threshold_strict": "0.35",
    }

    def _xor_encrypt(plaintext: str) -> str:
        data = plaintext.encode("utf-8")
        key_repeated = (key_bytes * ((len(data) // len(key_bytes)) + 1))[:len(data)]
        xored = bytes(a ^ b for a, b in zip(data, key_repeated))
        return base64.b64encode(xored).decode("ascii")

    encrypted = {k: _xor_encrypt(v) for k, v in secure_values.items()}
    key_repr = ", ".join(str(b) for b in key_bytes)
    encrypted_repr = ",\n    ".join(f'"{k}": "{v}"' for k, v in encrypted.items())
    content = (
        '"""Auto-generated by build_engine.py. DO NOT EDIT OR COMMIT."""\n'
        f'COMPILED_KEY = bytes([{key_repr}])\n'
        f'SECURE_VALUES = {{\n    {encrypted_repr},\n}}\n'
    )
    with open(key_file, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"Injected compile-time key + {len(secure_values)} encrypted values to {key_file}")
    return key_file


def build_engine():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.abspath(os.path.join(script_dir, "..", ".."))
    engine_script = os.path.join(script_dir, "engine_flask.py")
    output_dir = os.path.join(script_dir, "src-tauri", "binaries")

    os.makedirs(output_dir, exist_ok=True)

    _inject_compile_time_key(script_dir)

    machine = platform.machine().lower()
    system = platform.system().lower()
    if system == "windows":
        target = "x86_64-pc-windows-msvc"
        ext = ".exe"
    elif system == "darwin":
        target = f"{machine}-apple-darwin"
        ext = ""
    else:
        target = f"{machine}-unknown-linux-gnu"
        ext = ""

    output_name = f"xuandun-engine-{target}{ext}"

    cmd = [
        sys.executable, "-m", "nuitka",
        "--standalone",
        "--onefile",
        "--remove-output",
        "--lto=yes",
        "--strip",
        f"--output-filename={output_name}",
        f"--output-dir={output_dir}",
        "--enable-plugin=numpy",
        "--include-package=daoti_xuandun",
        "--nofollow-import-to=tkinter",
        "--nofollow-import-to=test",
        "--nofollow-import-to=unittest",
        "--nofollow-import-to=pytest",
        "--nofollow-import-to=mypy",
        engine_script,
    ]

    if system == "windows":
        cmd.extend([
            "--windows-disable-console",
            f"--windows-company-name=Daoti",
            f"--windows-product-name=XuanDun Engine",
            f"--windows-file-version=1.0.0",
            f"--windows-icon-from-ico={os.path.join(script_dir, 'src-tauri', 'icons', 'icon.ico')}",
        ])
    elif system == "darwin":
        cmd.extend([
            "--macos-app-mode=gui",
            f"--macos-app-name=XuanDun Engine",
        ])

    env = os.environ.copy()
    env["PYTHONPATH"] = os.path.join(project_root, "src")

    print(f"Building: {' '.join(cmd)}")
    result = subprocess.run(cmd, env=env, cwd=script_dir)

    if result.returncode == 0:
        print(f"Build successful: {os.path.join(output_dir, output_name)}")
    else:
        print(f"Build failed with code {result.returncode}")
        sys.exit(result.returncode)

if __name__ == "__main__":
    build_engine()
