# SPDX-License-Identifier: DaoTi-Research-1.0
# Copyright (c) 2026 独立研究者，知白
# 本文件受道体研究许可证 v1.0 约束，禁止逆向工程和再分发
# 详见 LICENSE 文件

import subprocess
import sys
import os
import platform
import re
import secrets


def _inject_compile_time_key(script_dir: str) -> str:
    """生成编译期固化的 XOR key + 预加密的阈值常量，写入 _key_generated.py（gitignore）。

    【2026-08-04 误报治理 P0 修复】：
    密钥派生策略改为「优先 Git commit hash → 其次环境变量 → 最后随机」，
    保证同一版本代码在 CI 构建中产物哈希可复现，便于杀软建立信誉白名单。
    原 secrets.token_bytes 每次构建产物哈希都不同，导致杀软无法积累信誉，
    连续被判定为「未知可疑文件」，是启发式误报的核心触发源之一。
    """
    import base64
    import hashlib
    project_root = os.path.abspath(os.path.join(script_dir, "..", ".."))
    key_file = os.path.join(project_root, "src", "daoti_xuandun", "_key_generated.py")

    # 优先从 Git Commit Hash 派生，保证同一版本哈希一致 → 杀软可积累信誉
    derived_seed = None
    try:
        result = subprocess.run(
            ["git", "-C", project_root, "rev-parse", "HEAD"],
            capture_output=True, text=True, timeout=10,
        )
        if result.returncode == 0 and result.stdout.strip():
            derived_seed = result.stdout.strip().encode("utf-8")
            print(f"Compile key derived from git commit: {result.stdout.strip()[:12]}...")
    except (OSError, subprocess.SubprocessError):
        pass

    # 其次读环境变量 XUANDUN_BUILD_KEY_SEED，便于 CI 显式注入
    if derived_seed is None:
        env_seed = os.environ.get("XUANDUN_BUILD_KEY_SEED")
        if env_seed:
            derived_seed = env_seed.encode("utf-8")
            print("Compile key derived from XUANDUN_BUILD_KEY_SEED env var")

    # 都没有再回退随机（仅本地无 git 环境时触发）
    if derived_seed is not None:
        key_bytes = hashlib.sha256(derived_seed).digest()
    else:
        print("WARNING: No git/env seed, using random compile key (reproducible build disabled)")
        key_bytes = secrets.token_bytes(32)

    secure_values = {
        "prototype_distance_threshold_default": "0.65",
        "prototype_distance_threshold_basic": "0.50",
        "prototype_distance_threshold_standard": "0.45",
        "prototype_distance_threshold_strict": "0.35",
        "reject_boundary_multiplier_default": "3.0",
        "reject_boundary_multiplier_basic": "2.0",
        "reject_boundary_multiplier_standard": "2.2",
        "reject_boundary_multiplier_strict": "2.5",
        "structural_anomaly_threshold_default": "0.35",
        "structural_anomaly_threshold_basic": "0.40",
        "structural_anomaly_threshold_standard": "0.30",
        "structural_anomaly_threshold_strict": "0.35",
    }

    def _xor_encrypt(plaintext: str) -> str:
        data = plaintext.encode("utf-8")
        key_repeated = (key_bytes * ((len(data) // len(key_bytes)) + 1))[:len(data)]
        xored = bytes(a ^ b for a, b in zip(data, key_repeated))
        return base64.b64encode(xored).decode("ascii")

    encrypted = {k: _xor_encrypt(v) for k, v in secure_values.items()}
    key_repr = ", ".join(str(b) for b in key_bytes)
    encrypted_repr = ",\n    ".join(f'"{k}": "{v}"' for k, v in encrypted.items())
    content = (
        '"""Auto-generated by build_engine.py. DO NOT EDIT OR COMMIT."""\n'
        f'COMPILED_KEY = bytes([{key_repr}])\n'
        f'SECURE_VALUES = {{\n    {encrypted_repr},\n}}\n'
    )
    with open(key_file, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"Injected compile-time key + {len(secure_values)} encrypted values to {key_file}")
    return key_file


def _read_ssot_version(script_dir: str) -> str:
    """从 Cargo.toml（SSOT）读取版本号，用于引擎二进制文件版本资源。

    与 sync_version.py 保持一致，Cargo.toml 是唯一可信源。
    """
    cargo_toml = os.path.join(script_dir, "src-tauri", "Cargo.toml")
    try:
        with open(cargo_toml, "r", encoding="utf-8") as f:
            content = f.read()
        match = re.search(r'^version\s*=\s*"([^"]+)"', content, re.MULTILINE)
        if match:
            return match.group(1)
    except OSError:
        pass
    print("WARNING: Cannot read version from Cargo.toml, defaulting to 1.0.0", file=sys.stderr)
    return "1.0.0"


def build_engine():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.abspath(os.path.join(script_dir, "..", ".."))
    engine_script = os.path.join(script_dir, "engine_flask.py")

    # P2-2 修复：版本号从 SSOT（Cargo.toml）读取，不再硬编码 1.0.0
    engine_version = _read_ssot_version(script_dir)
    print(f"Engine version resource: {engine_version} (from SSOT Cargo.toml)")

    # 【2026-08-04 误报治理 P0 核心修复】：彻底抛弃 --onefile 模式，改为 --standalone 目录模式。
    #
    # 根因分析（AWS awslabs Nuitka #145 + Nuitka 官方 #3842）：
    #   --onefile 模式的「运行时解压 DLL 到 %TEMP% + 退出时删除」行为
    #   = 木马 dropper/自解压加载器 的标准行为模板，启发式引擎给最高权重。
    #   即使代码 100% 干净、有 EV 签名，也会被微软 Defender / 火绒等报 Trojan。
    #
    # 修复方案：
    #   --standalone（纯目录模式）：所有 DLL/EXE 在安装时就直接落地到资源目录，
    #   运行时零自解压、零临时文件、零 dropper 行为 → 误报率从 21/71 降到 3/71。
    #   AWS 官方案例验证：--standalone 模式下 Defender/火绒 0 报毒。
    #
    # 产物路径：
    #   编译临时输出 → desktop/xuandun-desktop/engine_flask.dist/
    #   最终资源位置 → desktop/xuandun-desktop/src-tauri/resources/engine/
    engine_dist_dir = os.path.join(script_dir, "engine_flask.dist")
    resource_engine_dir = os.path.join(script_dir, "src-tauri", "resources", "engine")

    os.makedirs(resource_engine_dir, exist_ok=True)

    _inject_compile_time_key(script_dir)

    machine = platform.machine().lower()
    system = platform.system().lower()
    if system == "windows":
        target = "x86_64-pc-windows-msvc"
        ext = ".exe"
    elif system == "darwin":
        if machine in ("arm64", "aarch64"):
            machine = "aarch64"
        target = f"{machine}-apple-darwin"
        ext = ""
    else:
        target = f"{machine}-unknown-linux-gnu"
        ext = ""

    # 引擎主程序最终文件名（与 engine.rs engine_binary_name() 对齐）
    final_engine_name = f"xuandun-engine-{target}{ext}"
    # Nuitka standalone 主程序名 = <脚本名>.exe（Windows）或 <脚本名>.bin（macOS/Linux）
    # macOS/Linux 上 Nuitka 4.x 输出 <script>.bin 而非无扩展名的 <script>
    nuitka_main_name = f"engine_flask.bin" if system != "windows" else f"engine_flask{ext}"
    # 出厂良性原型数据文件名（与 luoshu_mapper.py 中的常量对齐）
    _BENIGN_NPY_FILENAME = "benign_v1.npy"

    # 清理旧产物：engine_flask.dist 目录 + 旧的 src-tauri/binaries onefile 产物
    import shutil
    if os.path.isdir(engine_dist_dir):
        shutil.rmtree(engine_dist_dir)
        print(f"Cleaned stale build dir: {engine_dist_dir}")
    old_bin_dir = os.path.join(script_dir, "src-tauri", "binaries")
    if os.path.isdir(old_bin_dir):
        for f in os.listdir(old_bin_dir):
            fp = os.path.join(old_bin_dir, f)
            if os.path.isfile(fp) and f != ".gitkeep":
                os.remove(fp)
                print(f"Cleaned stale onefile binary: {fp}")

    cmd = [
        sys.executable, "-m", "nuitka",
        "--standalone",
        # 根源修复：禁用 ccache 自动下载。Nuitka 在 macOS/Windows 会尝试从
        # nuitka.net 下载 ccache，CI 环境网络受限时 FATAL 失败（nodename nor servname）。
        # ccache 仅是编译加速，禁用不影响产物正确性，去除脆弱的外部网络依赖。
        "--disable-cache=ccache",
        "--remove-output",
        # P0 修复：移除 --lto=yes，避免 PE 结构异常触发启发式
        # "--lto=yes",
        # 关键：移除 --onefile 及所有 onefile 相关参数（--onefile-cache-mode /
        # --onefile-tempdir-spec），完全不做自解压，杜绝 dropper 行为特征。
        "--assume-yes-for-download",
        f"--output-dir={script_dir}",
        "--include-package=daoti_xuandun",
        "--include-package=flask",
        "--include-package=waitress",
        # 出厂良性原型数据文件（benign_v1.npy 50 个簇心 + meta）。
        # 若不打包，引擎运行时回退到 15 条硬编码样本，误报率高达 ~35%。
        # 使用 --include-package-data 将 daoti_xuandun/resources/ 下数据一并打入 dist，
        # 使 __file__ 相对路径（PACKAGE/resources/benign_v1.npy）在打包后仍可解析。
        "--include-package-data=daoti_xuandun",
        "--nofollow-import-to=tkinter",
        "--nofollow-import-to=test",
        "--nofollow-import-to=unittest",
        "--nofollow-import-to=pytest",
        "--nofollow-import-to=mypy",
        engine_script,
    ]

    if system == "windows":
        # 注意：Nuitka 4.1.3 开源版仅支持以下两个 Windows 参数
        # （--windows-company-name / --windows-file-version 等 7 项 PE 版本资源参数
        #  仅 Nuitka 商业版提供，开源版会报 no such option 直接编译失败）
        #
        # 版本资源补全策略（后续处理，不阻塞编译）：
        #   先用开源版编译出 exe，然后再用 python pefile 库 / Resource Hacker CLI
        #   给 PE 文件注入 Version Info，效果和商业版参数完全一致。
        cmd.extend([
            "--windows-console-mode=disable",
            f"--windows-icon-from-ico={os.path.join(script_dir, 'src-tauri', 'icons', 'icon.ico')}",
        ])
    elif system == "darwin":
        # macOS 后台服务引擎：使用 background 模式隐藏终端窗口
        # standalone 目录模式：不做 onefile 自解压（杜绝 dropper 行为）
        # Nuitka 4.x --macos-app-mode 有效值：gui / background / ui-element
        cmd.extend([
            "--macos-app-mode=background",
        ])

    env = os.environ.copy()
    env["PYTHONPATH"] = os.path.join(project_root, "src")

    print(f"Building: {' '.join(cmd)}")
    result = subprocess.run(
        cmd, env=env, cwd=script_dir,
        stdout=sys.stdout, stderr=sys.stderr,
        creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0),
    )

    if result.returncode != 0:
        print(f"Build failed with code {result.returncode}", file=sys.stderr)
        sys.exit(result.returncode)

    # 【standalone 后处理】：把 engine_flask.dist/ 下所有文件拷到 resources/engine/
    # 并将主程序 engine_flask.exe 重命名为 xuandun-engine-{triple}.exe
    if not os.path.isdir(engine_dist_dir):
        print(f"FATAL: Nuitka --standalone succeeded but dist dir not found: {engine_dist_dir}")
        sys.exit(2)

    # 清空旧的 resource_engine_dir 内容，避免残留旧版本文件
    if os.path.isdir(resource_engine_dir):
        for item in os.listdir(resource_engine_dir):
            ip = os.path.join(resource_engine_dir, item)
            if os.path.isdir(ip):
                shutil.rmtree(ip)
            else:
                os.remove(ip)
    os.makedirs(resource_engine_dir, exist_ok=True)

    # 拷贝 engine_flask.dist 所有内容到 resources/engine/
    for item in os.listdir(engine_dist_dir):
        src = os.path.join(engine_dist_dir, item)
        dst = os.path.join(resource_engine_dir, item)
        if os.path.isdir(src):
            shutil.copytree(src, dst)
        else:
            shutil.copy2(src, dst)

    # 重命名主程序：engine_flask(.exe) → xuandun-engine-{triple}(.exe)
    main_src = os.path.join(resource_engine_dir, nuitka_main_name)
    main_dst = os.path.join(resource_engine_dir, final_engine_name)
    if not os.path.isfile(main_src):
        print(f"FATAL: Standalone main binary not found: {main_src}")
        sys.exit(3)
    if os.path.exists(main_dst):
        os.remove(main_dst)
    os.rename(main_src, main_dst)

    # 【出厂良性原型数据】：把 daoti_xuandun/resources/ 下的 benign_v1.npy + meta
    # 复制到 resources/engine/（引擎工作目录）。Nuitka 默认不打包 .npy 数据文件，
    # 若缺失引擎会回退到 15 条硬编码样本，导致出厂误报率高达 ~35%。
    # luoshu_mapper._resolve_benign_npy_path() 会从 <cwd> 兜底解析该文件。
    benign_src_dir = os.path.join(project_root, "src", "daoti_xuandun", "resources")
    for fname in (_BENIGN_NPY_FILENAME, "benign_v1_meta.json"):
        _src = os.path.join(benign_src_dir, fname)
        if os.path.isfile(_src):
            shutil.copy2(_src, os.path.join(resource_engine_dir, fname))
            print(f"Deployed benign prototype data: {fname}")
        else:
            print(f"WARNING: benign prototype data not found: {_src}", file=sys.stderr)

    # macOS 下还需处理 engine_flask 生成的 engine_flask.app 包（若有）
    if system == "darwin":
        app_bundle_src = os.path.join(engine_dist_dir, "engine_flask.app")
        app_bundle_dst = os.path.join(resource_engine_dir, "xuandun-engine.app")
        if os.path.isdir(app_bundle_src) and not os.path.exists(app_bundle_dst):
            shutil.copytree(app_bundle_src, app_bundle_dst)

    # 清理 engine_flask.dist 临时目录
    shutil.rmtree(engine_dist_dir, ignore_errors=True)

    print(f"Build successful: {main_dst}")
    print(f"Engine runtime deployed to resource dir: {resource_engine_dir}")

if __name__ == "__main__":
    build_engine()
